// CREATION DE LA TABLE PIM PIVOTÉE TOUT EN GARDANT L'INCREMENTAL 

-- 1. Stored Procedure
CREATE OR REPLACE PROCEDURE IRRI_PROD.SILVER.REBUILD_ARTICLE_COMPLET_INFO()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS
DECLARE
    col_list STRING;
    create_sql STRING;
    current_cols ARRAY;
    new_cols ARRAY;
BEGIN
    SELECT ARRAY_AGG(COLUMN_NAME) WITHIN GROUP (ORDER BY COLUMN_NAME)
    INTO :current_cols
    FROM IRRI_PROD.INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = 'SILVER' AND TABLE_NAME = 'ARTICLE_COMPLET_INFO' AND COLUMN_NAME != 'SKU';

    SELECT ARRAY_AGG(UPPER(REGEXP_REPLACE(REGEXP_REPLACE(ATTRIBUTE_CODE, '[^A-Za-z0-9_]', '_'), '^([0-9])', '_\\1'))) WITHIN GROUP (ORDER BY ATTRIBUTE_CODE)
    INTO :new_cols
    FROM (SELECT DISTINCT ATTRIBUTE_CODE FROM IRRI_PROD.SILVER.ARTICLE_ATTRIBUTES_VALUE_FR WHERE LOWER(ATTRIBUTE_CODE) != 'sku');

    IF (:current_cols = :new_cols) THEN
        RETURN 'No schema change detected — skipped';
    END IF;

    INSERT INTO IRRI_PROD.SILVER.ARTICLE_PIM_COLUMN_CHANGE_LOG (TABLE_NAME, COLUMN_NAME, CHANGE_TYPE)
    SELECT 'ARTICLE_COMPLET_INFO', VALUE::VARCHAR, 'ADDED'
    FROM TABLE(FLATTEN(INPUT => :new_cols))
    WHERE VALUE::VARCHAR NOT IN (SELECT VALUE::VARCHAR FROM TABLE(FLATTEN(INPUT => :current_cols)));

    INSERT INTO IRRI_PROD.SILVER.ARTICLE_PIM_COLUMN_CHANGE_LOG (TABLE_NAME, COLUMN_NAME, CHANGE_TYPE)
    SELECT 'ARTICLE_COMPLET_INFO', VALUE::VARCHAR, 'REMOVED'
    FROM TABLE(FLATTEN(INPUT => :current_cols))
    WHERE VALUE::VARCHAR NOT IN (SELECT VALUE::VARCHAR FROM TABLE(FLATTEN(INPUT => :new_cols)));

    SELECT LISTAGG(
        CASE
            WHEN UPPER(ATTRIBUTE_CODE) IN ('HAUTEUR_CM','LARGEUR_CM','LONGUEUR_CM','HAUTEUR_CARTON_CM','LARGEUR_CARTON_CM','LONGUEUR_CARTON_CM','HAUTEUR_PALETTE_CM','LARGEUR_PALETTE_CM','LONGUEUR_PALETTE_CM','HAUTEUR_PRODUIT_CONDITIONNE_CM','LARGEUR_PRODUIT_CONDITIONNE_CM','LONGUEUR_PRODUIT_CONDITIONNE_CM','DIAMETRE_PRODUIT_CM','EPAISSEUR_LINER','LONGUEUR_DE_CABLE_METRE','LONGUEUR_MAXI_BASSIN_METRE','PROFONDEUR_DE_BAIGNADE_METRE')
            THEN '    CASE' ||
                 ' WHEN MAX(CASE WHEN ATTRIBUTE_CODE = ''' || ATTRIBUTE_CODE || ''' THEN CLEANED_ATTRIBUTE_VALUE END) LIKE ''%MILLIMETER%''' ||
                 ' THEN SPLIT_PART(MAX(CASE WHEN ATTRIBUTE_CODE = ''' || ATTRIBUTE_CODE || ''' THEN CLEANED_ATTRIBUTE_VALUE END), '' '', 1)::FLOAT / 1000' ||
                 ' WHEN MAX(CASE WHEN ATTRIBUTE_CODE = ''' || ATTRIBUTE_CODE || ''' THEN CLEANED_ATTRIBUTE_VALUE END) LIKE ''%CENTIMETER%''' ||
                 ' THEN SPLIT_PART(MAX(CASE WHEN ATTRIBUTE_CODE = ''' || ATTRIBUTE_CODE || ''' THEN CLEANED_ATTRIBUTE_VALUE END), '' '', 1)::FLOAT / 100' ||
                 ' WHEN MAX(CASE WHEN ATTRIBUTE_CODE = ''' || ATTRIBUTE_CODE || ''' THEN CLEANED_ATTRIBUTE_VALUE END) LIKE ''%MICRONS%''' ||
                 ' THEN SPLIT_PART(MAX(CASE WHEN ATTRIBUTE_CODE = ''' || ATTRIBUTE_CODE || ''' THEN CLEANED_ATTRIBUTE_VALUE END), '' '', 1)::FLOAT / 1000000' ||
                 ' WHEN MAX(CASE WHEN ATTRIBUTE_CODE = ''' || ATTRIBUTE_CODE || ''' THEN CLEANED_ATTRIBUTE_VALUE END) LIKE ''%METER%''' ||
                 ' THEN SPLIT_PART(MAX(CASE WHEN ATTRIBUTE_CODE = ''' || ATTRIBUTE_CODE || ''' THEN CLEANED_ATTRIBUTE_VALUE END), '' '', 1)::FLOAT' ||
                 ' END AS ' || UPPER(REGEXP_REPLACE(REGEXP_REPLACE(ATTRIBUTE_CODE, '[^A-Za-z0-9_]', '_'), '^([0-9])', '_\\1')) || '_METRE'
            WHEN UPPER(ATTRIBUTE_CODE) IN ('POIDS','POIDS_CARTON','POIDS_PALETTE','POIDS_PRODUIT_KG','POIDS_EN_EAU_KILOS','POIDS_VIDE_KILOS','CHARGE_DE_SABLE_KILOS','CONTENANCE_KILOS')
            THEN '    CASE' ||
                 ' WHEN MAX(CASE WHEN ATTRIBUTE_CODE = ''' || ATTRIBUTE_CODE || ''' THEN CLEANED_ATTRIBUTE_VALUE END) LIKE ''%MICROGRAM%''' ||
                 ' THEN SPLIT_PART(MAX(CASE WHEN ATTRIBUTE_CODE = ''' || ATTRIBUTE_CODE || ''' THEN CLEANED_ATTRIBUTE_VALUE END), '' '', 1)::FLOAT / 1000000000' ||
                 ' WHEN MAX(CASE WHEN ATTRIBUTE_CODE = ''' || ATTRIBUTE_CODE || ''' THEN CLEANED_ATTRIBUTE_VALUE END) LIKE ''%MILLIGRAM%''' ||
                 ' THEN SPLIT_PART(MAX(CASE WHEN ATTRIBUTE_CODE = ''' || ATTRIBUTE_CODE || ''' THEN CLEANED_ATTRIBUTE_VALUE END), '' '', 1)::FLOAT / 1000000' ||
                 ' WHEN MAX(CASE WHEN ATTRIBUTE_CODE = ''' || ATTRIBUTE_CODE || ''' THEN CLEANED_ATTRIBUTE_VALUE END) LIKE ''%GRAM%''' ||
                 ' THEN SPLIT_PART(MAX(CASE WHEN ATTRIBUTE_CODE = ''' || ATTRIBUTE_CODE || ''' THEN CLEANED_ATTRIBUTE_VALUE END), '' '', 1)::FLOAT / 1000' ||
                 ' WHEN MAX(CASE WHEN ATTRIBUTE_CODE = ''' || ATTRIBUTE_CODE || ''' THEN CLEANED_ATTRIBUTE_VALUE END) LIKE ''%KILOGRAM%''' ||
                 ' THEN SPLIT_PART(MAX(CASE WHEN ATTRIBUTE_CODE = ''' || ATTRIBUTE_CODE || ''' THEN CLEANED_ATTRIBUTE_VALUE END), '' '', 1)::FLOAT' ||
                 ' END AS ' || UPPER(REGEXP_REPLACE(REGEXP_REPLACE(ATTRIBUTE_CODE, '[^A-Za-z0-9_]', '_'), '^([0-9])', '_\\1')) || '_KG'
            WHEN UPPER(ATTRIBUTE_CODE) IN ('CONTENANCE_CAPACITE_LITRE','CONTENANCE_LITRE_BRUT')
            THEN '    CASE' ||
                 ' WHEN MAX(CASE WHEN ATTRIBUTE_CODE = ''' || ATTRIBUTE_CODE || ''' THEN CLEANED_ATTRIBUTE_VALUE END) LIKE ''%MILLILITER%''' ||
                 ' THEN SPLIT_PART(MAX(CASE WHEN ATTRIBUTE_CODE = ''' || ATTRIBUTE_CODE || ''' THEN CLEANED_ATTRIBUTE_VALUE END), '' '', 1)::FLOAT / 1000' ||
                 ' WHEN MAX(CASE WHEN ATTRIBUTE_CODE = ''' || ATTRIBUTE_CODE || ''' THEN CLEANED_ATTRIBUTE_VALUE END) LIKE ''%CUBIC_METER%''' ||
                 ' THEN SPLIT_PART(MAX(CASE WHEN ATTRIBUTE_CODE = ''' || ATTRIBUTE_CODE || ''' THEN CLEANED_ATTRIBUTE_VALUE END), '' '', 1)::FLOAT * 1000' ||
                 ' WHEN MAX(CASE WHEN ATTRIBUTE_CODE = ''' || ATTRIBUTE_CODE || ''' THEN CLEANED_ATTRIBUTE_VALUE END) LIKE ''%LITER%''' ||
                 ' THEN SPLIT_PART(MAX(CASE WHEN ATTRIBUTE_CODE = ''' || ATTRIBUTE_CODE || ''' THEN CLEANED_ATTRIBUTE_VALUE END), '' '', 1)::FLOAT' ||
                 ' END AS ' || UPPER(REGEXP_REPLACE(REGEXP_REPLACE(ATTRIBUTE_CODE, '[^A-Za-z0-9_]', '_'), '^([0-9])', '_\\1')) || '_NUM'
            WHEN UPPER(ATTRIBUTE_CODE) = 'DEBIT_M3_HEURE'
            THEN '    CASE' ||
                 ' WHEN MAX(CASE WHEN ATTRIBUTE_CODE = ''' || ATTRIBUTE_CODE || ''' THEN CLEANED_ATTRIBUTE_VALUE END) LIKE ''%MILLILITER_PER_HOUR%''' ||
                 ' THEN SPLIT_PART(MAX(CASE WHEN ATTRIBUTE_CODE = ''' || ATTRIBUTE_CODE || ''' THEN CLEANED_ATTRIBUTE_VALUE END), '' '', 1)::FLOAT / 1000000' ||
                 ' WHEN MAX(CASE WHEN ATTRIBUTE_CODE = ''' || ATTRIBUTE_CODE || ''' THEN CLEANED_ATTRIBUTE_VALUE END) LIKE ''%LITER_PER_MINUTE%''' ||
                 ' THEN SPLIT_PART(MAX(CASE WHEN ATTRIBUTE_CODE = ''' || ATTRIBUTE_CODE || ''' THEN CLEANED_ATTRIBUTE_VALUE END), '' '', 1)::FLOAT * 0.06' ||
                 ' WHEN MAX(CASE WHEN ATTRIBUTE_CODE = ''' || ATTRIBUTE_CODE || ''' THEN CLEANED_ATTRIBUTE_VALUE END) LIKE ''%LITER_PER_HOUR%''' ||
                 ' THEN SPLIT_PART(MAX(CASE WHEN ATTRIBUTE_CODE = ''' || ATTRIBUTE_CODE || ''' THEN CLEANED_ATTRIBUTE_VALUE END), '' '', 1)::FLOAT / 1000' ||
                 ' WHEN MAX(CASE WHEN ATTRIBUTE_CODE = ''' || ATTRIBUTE_CODE || ''' THEN CLEANED_ATTRIBUTE_VALUE END) LIKE ''%CUBIC_METER_PER_HOUR%''' ||
                 ' THEN SPLIT_PART(MAX(CASE WHEN ATTRIBUTE_CODE = ''' || ATTRIBUTE_CODE || ''' THEN CLEANED_ATTRIBUTE_VALUE END), '' '', 1)::FLOAT' ||
                 ' END AS DEBIT_M3_HEURE_NUM'
            WHEN UPPER(ATTRIBUTE_CODE) IN ('DEBIT_LITRES_HEURE','DEBIT_LITRE_HEURE_MAXIMUM','DEBIT_LITRE_HEURE_MINIMUM')
            THEN '    CASE' ||
                 ' WHEN MAX(CASE WHEN ATTRIBUTE_CODE = ''' || ATTRIBUTE_CODE || ''' THEN CLEANED_ATTRIBUTE_VALUE END) LIKE ''%MILLILITER%''' ||
                 ' THEN SPLIT_PART(MAX(CASE WHEN ATTRIBUTE_CODE = ''' || ATTRIBUTE_CODE || ''' THEN CLEANED_ATTRIBUTE_VALUE END), '' '', 1)::FLOAT / 1000' ||
                 ' ELSE SPLIT_PART(MAX(CASE WHEN ATTRIBUTE_CODE = ''' || ATTRIBUTE_CODE || ''' THEN CLEANED_ATTRIBUTE_VALUE END), '' '', 1)::FLOAT' ||
                 ' END AS ' || UPPER(REGEXP_REPLACE(REGEXP_REPLACE(ATTRIBUTE_CODE, '[^A-Za-z0-9_]', '_'), '^([0-9])', '_\\1')) || '_NUM'
            WHEN UPPER(ATTRIBUTE_CODE) IN ('VOLUME_PISCINE_MAX_M3','VOLUME_BASSIN')
            THEN '    CASE' ||
                 ' WHEN MAX(CASE WHEN ATTRIBUTE_CODE = ''' || ATTRIBUTE_CODE || ''' THEN CLEANED_ATTRIBUTE_VALUE END) LIKE ''%LITER%''' ||
                 ' THEN SPLIT_PART(MAX(CASE WHEN ATTRIBUTE_CODE = ''' || ATTRIBUTE_CODE || ''' THEN CLEANED_ATTRIBUTE_VALUE END), '' '', 1)::FLOAT / 1000' ||
                 ' WHEN MAX(CASE WHEN ATTRIBUTE_CODE = ''' || ATTRIBUTE_CODE || ''' THEN CLEANED_ATTRIBUTE_VALUE END) LIKE ''%CUBIC_METER%''' ||
                 ' THEN SPLIT_PART(MAX(CASE WHEN ATTRIBUTE_CODE = ''' || ATTRIBUTE_CODE || ''' THEN CLEANED_ATTRIBUTE_VALUE END), '' '', 1)::FLOAT' ||
                 ' ELSE TRY_TO_DOUBLE(MAX(CASE WHEN ATTRIBUTE_CODE = ''' || ATTRIBUTE_CODE || ''' THEN CLEANED_ATTRIBUTE_VALUE END))' ||
                 ' END AS ' || UPPER(REGEXP_REPLACE(REGEXP_REPLACE(ATTRIBUTE_CODE, '[^A-Za-z0-9_]', '_'), '^([0-9])', '_\\1')) || '_M3'
            WHEN UPPER(ATTRIBUTE_CODE) = 'PUISSANCE_WATT'
            THEN '    CASE' ||
                 ' WHEN MAX(CASE WHEN ATTRIBUTE_CODE = ''' || ATTRIBUTE_CODE || ''' THEN CLEANED_ATTRIBUTE_VALUE END) LIKE ''%KILOWATT%''' ||
                 ' THEN SPLIT_PART(MAX(CASE WHEN ATTRIBUTE_CODE = ''' || ATTRIBUTE_CODE || ''' THEN CLEANED_ATTRIBUTE_VALUE END), '' '', 1)::FLOAT * 1000' ||
                 ' WHEN MAX(CASE WHEN ATTRIBUTE_CODE = ''' || ATTRIBUTE_CODE || ''' THEN CLEANED_ATTRIBUTE_VALUE END) LIKE ''%WATT%''' ||
                 ' THEN SPLIT_PART(MAX(CASE WHEN ATTRIBUTE_CODE = ''' || ATTRIBUTE_CODE || ''' THEN CLEANED_ATTRIBUTE_VALUE END), '' '', 1)::FLOAT' ||
                 ' END AS PUISSANCE_WATT_NUM'
            WHEN UPPER(ATTRIBUTE_CODE) IN ('TAUX_TVA')
            THEN '    TRY_TO_NUMBER(REPLACE(MAX(CASE WHEN ATTRIBUTE_CODE = ''' || ATTRIBUTE_CODE || ''' THEN CLEANED_ATTRIBUTE_VALUE END), '','', ''.'')) AS TAUX_TVA'
            WHEN UPPER(ATTRIBUTE_CODE) IN ('LISTE_20_80')
            THEN '    COALESCE(MAX(CASE WHEN ATTRIBUTE_CODE = ''' || ATTRIBUTE_CODE || ''' THEN CLEANED_ATTRIBUTE_VALUE END) = ''true'', FALSE) AS ' || UPPER(REGEXP_REPLACE(REGEXP_REPLACE(ATTRIBUTE_CODE, '[^A-Za-z0-9_]', '_'), '^([0-9])', '_\\1'))
            WHEN UPPER(ATTRIBUTE_CODE) IN ('NOMBRE_COLIS','QUANTITE_CARTON','QUANTITE_CARTON_MAGASIN','QUANTITE_MINIMUM_ACHAT','QUANTITE_PAR_PALETTE','VOLUME_ADR_M3','NBR_MARCHES','NOMBRE_DE_BUSES','DENSITE_G')
            THEN '    TRY_TO_DOUBLE(MAX(CASE WHEN ATTRIBUTE_CODE = ''' || ATTRIBUTE_CODE || ''' THEN CLEANED_ATTRIBUTE_VALUE END)) AS ' || UPPER(REGEXP_REPLACE(REGEXP_REPLACE(ATTRIBUTE_CODE, '[^A-Za-z0-9_]', '_'), '^([0-9])', '_\\1'))
            WHEN UPPER(ATTRIBUTE_CODE) IN ('INTENSITE_AMPERES','AMPERES','PRESSION_MAX','PRESSION_DE_FONCTIONNEMENT','NIVEAU_SONORE','TEMPERATURE_EAU_MAX','SURFACE_DE_NAGE','COP','CAPACITE_DE_SOUFFLAGE','PUISSANCE_ABSORBEE','PUISSANCE_CV','PUISSANCE_DE_CHAUFFE','PUISSANCE_RESTITUEE','PUISSANCE_SURPRESSEUR','SECTION_DE_CABLE','PRODUCTION_DE_CHLORE','TAUX_DE_SEL_DE_FONCTIONNEMENT','FINESSE_DE_FILTRATION_MICRONS','GRAMMAGE_TOILE','HAUTEUR_MANOMETRIQUE','DOSOLOGIE','DEBIT_INJECTION','GRANULOMETRIE','PORTEE','PORTEE_MAX')
            THEN '    TRY_TO_DOUBLE(SPLIT_PART(MAX(CASE WHEN ATTRIBUTE_CODE = ''' || ATTRIBUTE_CODE || ''' THEN CLEANED_ATTRIBUTE_VALUE END), '' '', 1)) AS ' || UPPER(REGEXP_REPLACE(REGEXP_REPLACE(ATTRIBUTE_CODE, '[^A-Za-z0-9_]', '_'), '^([0-9])', '_\\1')) || '_NUM'
            ELSE '    MAX(CASE WHEN ATTRIBUTE_CODE = ''' || ATTRIBUTE_CODE || ''' THEN CLEANED_ATTRIBUTE_VALUE END) AS ' ||
                 UPPER(REGEXP_REPLACE(REGEXP_REPLACE(ATTRIBUTE_CODE, '[^A-Za-z0-9_]', '_'), '^([0-9])', '_\\1'))
        END,
        ',\n'
    ) WITHIN GROUP (ORDER BY ATTRIBUTE_CODE)
    INTO :col_list
    FROM (SELECT DISTINCT ATTRIBUTE_CODE FROM IRRI_PROD.SILVER.ARTICLE_ATTRIBUTES_VALUE_FR WHERE LOWER(ATTRIBUTE_CODE) != 'sku');

    create_sql := '
CREATE OR REPLACE DYNAMIC TABLE IRRI_PROD.SILVER.ARTICLE_COMPLET_INFO
    TARGET_LAG = ''1 day''
    REFRESH_MODE = INCREMENTAL
    INITIALIZE = ON_CREATE
    WAREHOUSE = COMPUTE_WH
AS
with pim AS (SELECT
    SKU AS CODE_ARTICLE,
' || :col_list || '
FROM IRRI_PROD.SILVER.ARTICLE_ATTRIBUTES_VALUE_FR
GROUP BY SKU)
SELECT pim.*, ak.ITEM:family::STRING AS FAMILLE_PIM, x3.* EXCLUDE (ARTICLE_COMPLET, FAMILLE_X3, SOUS_FAMILLE_X3, SOUS_SOUS_FAMILLE_X3, CODE)
FROM pim
LEFT JOIN IRRI_PROD.BRONZE.AKENEO_PRODUCTS_RAW_DATA ak ON pim.CODE_ARTICLE = ak.SKU
LEFT JOIN IRRI_PROD.SILVER.ARTICLE_X3_ATTRIBUTES x3 ON pim.CODE_ARTICLE = x3.code';

    EXECUTE IMMEDIATE :create_sql;
    
    RETURN 'Dynamic Tables recreated with ' || ARRAY_SIZE(:new_cols) || ' columns (+ downstream refreshed)';
END;

CALL IRRI_PROD.SILVER.REBUILD_ARTICLE_COMPLET_INFO();

CREATE TABLE IRRI_PROD.SILVER.ARTICLE_PIM_COLUMN_CHANGE_LOG (TABLE_NAME VARCHAR, COLUMN_NAME VARCHAR, CHANGE_TYPE VARCHAR, CHANGE_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP());

ALTER DYNAMIC TABLE IRRI_PROD.SILVER.ARTICLE_COMPLET_INFO REFRESH;

-- 2. Task planifiée (1x par jour)
CREATE OR REPLACE TASK IRRI_PROD.SILVER.TASK_REBUILD_ARTICLE_COMPLET_INFO
    WAREHOUSE = COMPUTE_WH
    SCHEDULE = 'USING CRON 0 3 * * * Europe/Paris'
AS
    CALL IRRI_PROD.SILVER.REBUILD_ARTICLE_COMPLET_INFO();

-- 3. Activer la task
ALTER TASK IRRI_PROD.SILVER.TASK_REBUILD_ARTICLE_COMPLET_INFO RESUME;

SELECT * FROM IRRI_PROD.SILVER.ARTICLE_COMPLET_INFO;


