SELECT * FROM ARTICLE_ATTRIBUTES_VALUE_ES WHERE  sku = '437745';

SELECT * FROM TARIF_CESSION_ESPAGNE_REAPPRO where code_article = '437745';

SELECT * FROM TARIF_CESSION_ESPAGNE where code_article = '437745';