SELECT * FROM IRRI_PROD.GOLD_EXT.ODOOESP_TARIF_ACHAT where code_article = '443874';

SELECT * FROM ETL_PROD.LOG.ODOOESP_TARIF_ACHAT where code_article ='443874';

SELECT * FROM IRRI_PROD.GOLD_EXT.ODOOESP_ARTICLE_CONDITIONNEMENT;

ALTER DYNAMIC TABLE IRRI_PROD.GOLD_EXT.ODOOESP_ARTICLE_CONDITIONNEMENT REFRESH;

 