SELECT DISTINCT ta.CODE_ARTICLE,a.last_message FROM ETL_PROD.LOG.ODOOESP_TARIF_ACHAT ta JOIN ETL_PROD.LOG.ODOOESP_ARTICLE a ON ta.CODE_ARTICLE = a.CODE_ARTICLE WHERE ta.result = 0 ;

SELECT CODE_ARTICLE, last_message FROM ETL_PROD.LOG.ODOOESP_ARTICLE where last_message is null;

SELECT a.CODE_ARTICLE
FROM ETL_PROD.LOG.ODOOESP_ARTICLE a
LEFT JOIN ETL_PROD.LOG.ODOOESP_TARIF_ACHAT ta ON ta.CODE_ARTICLE = a.CODE_ARTICLE
WHERE ta.CODE_ARTICLE IS NULL
