SELECT DISTINCT CODE_ARTICLE FROM ETL_PROD.LOG.ODOOESP_ARTICLE where result=0 and last_message is not null;

SELECT CODE_ARTICLE, COUNT(*) as nb 
FROM ETL_PROD.LOG.ODOOESP_ARTICLE
GROUP BY CODE_ARTICLE
HAVING nb > 1;

SELECT * FROM IRRI_PROD.BRONZE.AKENEO_PRODUCTS_RAW_DATA where SKU = '436220';

SELECT * FROM ODOOESP_ARTICLE;

SELECT * FROM ODOOESP_ARTICLE FULL JOIN ETL_PROD.LOG.ODOOESP_ARTICLE etl ON ODOOESP_ARTICLE.CODE_ARTICLE = etl.CODE_ARTICLE
WHERE ODOOESP_ARTICLE.code_article IS NULL or etl.code_article is null ;

INSERT INTO ETL_PROD.LOG.ODOOESP_ARTICLE
SELECT DISTINCT *
FROM ETL_PROD.LOG.ODOOESP_ARTICLE BEFORE (STATEMENT => '01c3ad68-0001-b11c-0001-322a04671482')
WHERE CODE_ARTICLE IN ('704008','702014','704001','704017','709074','709082');

SELECT * FROM ETL_PREPROD.LOG.ODOOESP_ARTICLE where result = false and last_message is null;

SELECT * FROM IRRI_PROD.BRONZE.SAGEX3_ZZVITEM_PIM where itmref_0 in (SELECT CODE_ARTICLE FROM ETL_PROD.LOG.ODOOESP_ARTICLE where result = false and last_message is null);

SELECT * FROM IRRI_PROD.GOLD_EXT.ODOOESP_ARTICLE;

SELECT * FROM ETL_PROD.LOG.ODOOESP_ARTICLE where result=0;

SELECT * FROM IRRI_PROD.GOLD_EXT.ODOOESP_TARIF_ACHAT;

SELECT * FROM IRRI_PROD.GOLD_EXT.ODOOESP_ARTICLE_CONDITIONNEMENT;

SELECT * FROM IRRI_PROD.GOLD_EXT.ODOOESP_ARTICLE where code_article = '442186';

SELECT * FROM IRRI_PROD.GOLD_EXT.ODOOESP_TARIF_ACHAT where unite_base ilike '%m%'

   


