SELECT * FROM ODOOESP_TARIF_ACHAT;

SELECT * FROM ETL_PROD.LOG.ODOOESP_CONDITIONNEMENT order by last_exec desc;

SELECT * FROM IRRI_PROD.GOLD_EXT.ODOOESP_ARTICLE_CONDITIONNEMENT;

ALTER DYNAMIC TABLE IRRI_PROD.GOLD_EXT.ODOOESP_ARTICLE_CONDITIONNEMENT REFRESH;

 