create or replace dynamic table IRRI_DEV.GOLD.ARTICLE_SEARCH_DOCUMENT(
	SKU,
	FULL_DOC
) target_lag = '1 day' refresh_mode = INCREMENTAL initialize = ON_CREATE warehouse = COMPUTE_WH
 as
SELECT
   SKU,
        LISTAGG(ATTRIBUTE_CODE || ': ' || CLEANED_ATTRIBUTE_VALUE, '\n\n') 
            WITHIN GROUP (ORDER BY CASE ATTRIBUTE_CODE
                WHEN 'DESIGNATION_COMMERCIALE' THEN 1
                WHEN 'DESIGNATION_X3' THEN 2
                WHEN 'FOURNISSEUR_DESCRIPTIF_COMMERCIAL' THEN 3
                WHEN 'DESCRIPTIF_COMMERCIAL_LONG_1' THEN 4
                WHEN 'DESCRIPTIF_COMMERCIAL_LONG' THEN 5
                WHEN 'LES_CONSEILS_DE_PRO_TEXTE' THEN 6
                WHEN 'AVANTAGES_PRODUIT_COURTS' THEN 7
                WHEN 'DESCRIPTIF_CATALOGUE' THEN 8
                WHEN 'LES_PLUS_PRODUIT_1' THEN 9
                WHEN 'LES_PLUS_PRODUIT_2' THEN 10
                WHEN 'LES_PLUS_PRODUIT_3' THEN 11
            END)
           AS FULL_DOC
    FROM IRRI_DEV.SILVER.ARTICLE_ATTRIBUTES_VALUE_FR
    WHERE ATTRIBUTE_CODE IN ('DESIGNATION_COMMERCIALE', 'DESIGNATION_X3', 'FOURNISSEUR_DESCRIPTIF_COMMERCIAL','DESCRIPTIF_COMMERCIAL_LONG_1','DESCRIPTIF_COMMERCIAL_LONG','LES_CONSEILS_DE_PRO_TEXTE','AVANTAGES_PRODUIT_COURTS','DESCRIPTIF_CATALOGUE','LES_PLUS_PRODUIT_1','LES_PLUS_PRODUIT_2','LES_PLUS_PRODUIT_3')
    GROUP BY SKU
;


CREATE OR REPLACE CORTEX SEARCH SERVICE IRRI_DEV.GOLD.ARTICLE_SEARCH_DOCUMENT
ON FULL_DOC
ATTRIBUTES SKU, FAMILLE_X3, MARQUE_COMMERCIALE, ACTIF_X3
WAREHOUSE = COMPUTE_WH
TARGET_LAG = '1 day'
AS
    SELECT
        a.*,
        c.VALUE::STRING AS SEARCH_DOC
    FROM IRRI_DEV.GOLD.ARTICLE_SEARCH_DOCUMENT a,
    TABLE(FLATTEN(
        SNOWFLAKE.CORTEX.SPLIT_TEXT_RECURSIVE_CHARACTER(
            a.FULL_DOC, 'none', 1800, 200
        )
    )) c;

    CREATE OR REPLACE DYNAMIC TABLE IRRI_DEV.GOLD.ARTICLE_SEARCH_DOCUMENT(
	SKU,
    FAMILLE_X3,
    MARQUE_COMMERCIALE,
    ACTIF_X3,
	FULL_DOC
) target_lag = '1 day' refresh_mode = INCREMENTAL initialize = ON_CREATE warehouse = COMPUTE_WH
 as
SELECT
   a.SKU,
    article.FAMILLE_X3,
    article.MARQUE_COMMERCIALE,
    article.ACTIF_X3,
        LISTAGG(a.ATTRIBUTE_CODE || ': ' || a.CLEANED_ATTRIBUTE_VALUE, '\n\n') 
            WITHIN GROUP (ORDER BY CASE a.ATTRIBUTE_CODE
                WHEN 'DESIGNATION_COMMERCIALE' THEN 1
                WHEN 'DESIGNATION_X3' THEN 2
                WHEN 'FOURNISSEUR_DESCRIPTIF_COMMERCIAL' THEN 3
                WHEN 'DESCRIPTIF_COMMERCIAL_LONG_1' THEN 4
                WHEN 'DESCRIPTIF_COMMERCIAL_LONG' THEN 5
                WHEN 'LES_CONSEILS_DE_PRO_TEXTE' THEN 6
                WHEN 'AVANTAGES_PRODUIT_COURTS' THEN 7
                WHEN 'DESCRIPTIF_CATALOGUE' THEN 8
                WHEN 'LES_PLUS_PRODUIT_1' THEN 9
                WHEN 'LES_PLUS_PRODUIT_2' THEN 10
                WHEN 'LES_PLUS_PRODUIT_3' THEN 11
            END)
           AS FULL_DOC
    FROM IRRI_DEV.SILVER.ARTICLE_ATTRIBUTES_VALUE_FR a
    LEFT JOIN IRRI_DEV.SILVER.ARTICLE_COMPLET_INFO article
        ON a.SKU = article.SKU
    GROUP BY a.SKU, article.FAMILLE_X3, article.MARQUE_COMMERCIALE, article.ACTIF_X3
;

