CREATE OR REPLACE DYNAMIC TABLE ARTICLE_SEARCH_DOCUMENT
    TARGET_LAG = '1 day'
    REFRESH_MODE = INCREMENTAL
    WAREHOUSE = 'COMPUTE_WH'
AS
SELECT article.CODE_ARTICLE,
article.FAMILLE_X3,
article.MARQUE_COMMERCIALE,
article.LIBELLE_FAMILLE_X3,
LISTAGG(attributes.ATTRIBUTE_CODE || ':' || attributes.CLEANED_ATTRIBUTE_VALUE || '/n/n')
WITHIN GROUP (ORDER BY CASE attributes.ATTRIBUTE_CODE 
                WHEN 'DESIGNATION_COMMERCIALE' THEN 1
                WHEN 'DESIGNATION_X3' THEN 2
                WHEN 'FOURNISSEUR_DESCRIPTIF_COMMERCIAL' THEN 3
                WHEN 'DESCRIPTIF_COMMERCIAL_LONG_1' THEN 4
                WHEN 'DESCRIPTIF_COMMERCIAL_LONG' THEN 5
                WHEN 'LES_CONSEILS_DE_PRO_TEXTE' THEN 6
                WHEN 'AVANTAGES_PRODUIT_COURTS' THEN 7
                WHEN 'DESCRIPTIF_CATALOGUE' THEN 8
                WHEN 'LES_PLUS_PRODUIT_1' THEN 9
                WHEN 'LES_PLUS_PRODUIT_2' THEN 10
                WHEN 'LES_PLUS_PRODUIT_3' THEN 11
END) AS CORTEX_SEARCH_DOCUMENT
FROM IRRI_PROD.SILVER.ARTICLE_COMPLET_INFO article
LEFT JOIN IRRI_PROD.SILVER.ARTICLE_ATTRIBUTES_VALUE_FR attributes ON article.CODE_ARTICLE = attributes.sku
GROUP BY article.CODE_ARTICLE,article.FAMILLE_X3, article.MARQUE_COMMERCIALE, article.LIBELLE_FAMILLE_X3;