SELECT * FROM GEOGRAPHIE_CODE_POSTAL;

DROP STAGE IRRI_PROD.GOLD.GEOGRAPHIE_CODE_POSTAL_STAGE;

CREATE STAGE IRRI_PROD.GOLD.GEOGRAPHIE_CODE_POSTAL_STAGE;

CREATE OR REPLACE FILE FORMAT IRRI_PROD.GOLD.CSV_SEMICOLON
    TYPE='CSV' FIELD_DELIMITER=';' FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1 ENCODING='UTF-8';

CREATE OR REPLACE TABLE IRRI_PROD.GOLD.GEOGRAPHIE_CODE_POSTAL (
    CODE_POSTAL,
    NUTS3_CODE,
    CODE_DEPARTEMENT,
    CODE_PAYS
) AS
SELECT DISTINCT
    csv.$1 AS CODE_POSTAL,
    csv.$2 AS NUTS3_CODE,
    csv.$3 AS CODE_DEPARTEMENT,
    csv.$4 AS CODE_PAYS
FROM @IRRI_PROD.GOLD.GEOGRAPHIE_CODE_POSTAL_STAGE/codes_postaux_france.csv
    (FILE_FORMAT => 'IRRI_PROD.GOLD.CSV_SEMICOLON') csv;

