-- 1. Stored Procedure : une seule Dynamic Table ARTICLE_COMPLET_INFO
--    fusionne le pivot PIM + JOIN X3 + transformations
CREATE OR REPLACE PROCEDURE IRRI_DEV.SILVER.REBUILD_ARTICLE_COMPLET_INFO()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS
DECLARE
    col_list STRING;
    create_sql STRING;
    current_cols ARRAY;
    new_cols ARRAY;
BEGIN
    SELECT ARRAY_AGG(COLUMN_NAME) WITHIN GROUP (ORDER BY COLUMN_NAME)
    INTO :current_cols
    FROM IRRI_DEV.INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = 'SILVER' AND TABLE_NAME = 'ARTICLE_COMPLET_INFO'
      AND COLUMN_NAME NOT IN ('SKU','CONTENANCE_LITRES','TAUX_TVA','NOMBRE_COLIS',
          'QUANTITE_CARTON_MAGASIN','QUANTITE_CARTON','QUANTITE_MINIMUM_ACHAT',
          'QUANTITE_PAR_PALETTE','VOLUME_ADR_M3','VOLUME_BASSIN','CONTENANCE_LITRE_BRUT',
          'HAUTEUR_METRE')
      AND COLUMN_NAME NOT IN (
          SELECT COLUMN_NAME FROM IRRI_DEV.INFORMATION_SCHEMA.COLUMNS
          WHERE TABLE_SCHEMA = 'SILVER' AND TABLE_NAME = 'ARTICLE_X3_ATTRIBUTES'
      );

    SELECT ARRAY_AGG(UPPER(REGEXP_REPLACE(REGEXP_REPLACE(ATTRIBUTE_CODE, '[^A-Za-z0-9_]', '_'), '^([0-9])', '_\\1'))) WITHIN GROUP (ORDER BY ATTRIBUTE_CODE)
    INTO :new_cols
    FROM (SELECT DISTINCT ATTRIBUTE_CODE FROM IRRI_PREPROD.SILVER.ARTICLE_ATTRIBUTES_VALUE_FR WHERE LOWER(ATTRIBUTE_CODE) != 'sku');

    IF (:current_cols = :new_cols) THEN
        RETURN 'No schema change detected — skipped';
    END IF;

    INSERT INTO IRRI_DEV.SILVER.ARTICLE_PIM_COLUMN_CHANGE_LOG (TABLE_NAME, COLUMN_NAME, CHANGE_TYPE)
    SELECT 'ARTICLE_COMPLET_INFO', VALUE::VARCHAR, 'ADDED'
    FROM TABLE(FLATTEN(INPUT => :new_cols))
    WHERE VALUE::VARCHAR NOT IN (SELECT VALUE::VARCHAR FROM TABLE(FLATTEN(INPUT => :current_cols)));

    INSERT INTO IRRI_DEV.SILVER.ARTICLE_PIM_COLUMN_CHANGE_LOG (TABLE_NAME, COLUMN_NAME, CHANGE_TYPE)
    SELECT 'ARTICLE_COMPLET_INFO', VALUE::VARCHAR, 'REMOVED'
    FROM TABLE(FLATTEN(INPUT => :current_cols))
    WHERE VALUE::VARCHAR NOT IN (SELECT VALUE::VARCHAR FROM TABLE(FLATTEN(INPUT => :new_cols)));

    SELECT LISTAGG(
        '    MAX(CASE WHEN pim_src.ATTRIBUTE_CODE = ''' || ATTRIBUTE_CODE || ''' THEN pim_src.CLEANED_ATTRIBUTE_VALUE END) AS ' ||
        UPPER(REGEXP_REPLACE(REGEXP_REPLACE(ATTRIBUTE_CODE, '[^A-Za-z0-9_]', '_'), '^([0-9])', '_\\1')),
        ',\n'
    ) WITHIN GROUP (ORDER BY ATTRIBUTE_CODE)
    INTO :col_list
    FROM (SELECT DISTINCT ATTRIBUTE_CODE FROM IRRI_PREPROD.SILVER.ARTICLE_ATTRIBUTES_VALUE_FR WHERE LOWER(ATTRIBUTE_CODE) != 'sku');

    create_sql := '
CREATE OR REPLACE DYNAMIC TABLE IRRI_DEV.SILVER.ARTICLE_COMPLET_INFO
    TARGET_LAG = ''1 day''
    REFRESH_MODE = INCREMENTAL
    INITIALIZE = ON_CREATE
    WAREHOUSE = COMPUTE_WH
AS
WITH pim AS (
    SELECT
        SKU,
' || :col_list || '
    FROM IRRI_PREPROD.SILVER.ARTICLE_ATTRIBUTES_VALUE_FR pim_src
    GROUP BY SKU
)
SELECT
    pim.* EXCLUDE (ARTICLE_COMPLET, FAMILLE_X3, SOUS_FAMILLE_X3, SOUS_SOUS_FAMILLE_X3, TAUX_TVA, NOMBRE_COLIS, QUANTITE_CARTON, QUANTITE_CARTON_MAGASIN, QUANTITE_MINIMUM_ACHAT, QUANTITE_PAR_PALETTE, VOLUME_ADR_M3, VOLUME_BASSIN),
    x3.* EXCLUDE(CODE),
    CASE
        WHEN pim.CONTENANCE_CAPACITE_LITRE LIKE ''%MILLILITER%''
            THEN REGEXP_SUBSTR(pim.CONTENANCE_CAPACITE_LITRE, ''([0-9.]+)'', 1, 1, ''e'')::FLOAT / 1000
        WHEN pim.CONTENANCE_CAPACITE_LITRE LIKE ''%CUBIC_METER%''
            THEN REGEXP_SUBSTR(pim.CONTENANCE_CAPACITE_LITRE, ''([0-9.]+)'', 1, 1, ''e'')::FLOAT * 1000
        WHEN pim.CONTENANCE_CAPACITE_LITRE LIKE ''%LITER%''
            THEN REGEXP_SUBSTR(pim.CONTENANCE_CAPACITE_LITRE, ''([0-9.]+)'', 1, 1, ''e'')::FLOAT
    END AS CONTENANCE_LITRES,
    TRY_TO_NUMBER(REPLACE(pim.TAUX_TVA,'','',''.'')) AS TAUX_TVA,
    CAST(pim.NOMBRE_COLIS AS NUMBER) AS NOMBRE_COLIS,
    CAST(pim.QUANTITE_CARTON_MAGASIN AS NUMBER) AS QUANTITE_CARTON_MAGASIN,
    CAST(pim.QUANTITE_CARTON AS NUMBER) AS QUANTITE_CARTON,
    CAST(pim.QUANTITE_MINIMUM_ACHAT AS NUMBER) AS QUANTITE_MINIMUM_ACHAT,
    CAST(pim.QUANTITE_PAR_PALETTE AS NUMBER) AS QUANTITE_PAR_PALETTE,
    CAST(pim.VOLUME_ADR_M3 AS NUMBER) AS VOLUME_ADR_M3,
    CAST(pim.VOLUME_BASSIN AS NUMBER) AS VOLUME_BASSIN,
    pim.CONTENANCE_CAPACITE_LITRE AS CONTENANCE_LITRE_BRUT,
    CASE
        WHEN pim.HAUTEUR_CM LIKE ''%MILLIMETER%''
            THEN SPLIT_PART(pim.HAUTEUR_CM, '' '', 1)::FLOAT / 1000
        WHEN pim.HAUTEUR_CM LIKE ''%CENTIMETER%''
            THEN SPLIT_PART(pim.HAUTEUR_CM, '' '', 1)::FLOAT / 100
        WHEN pim.HAUTEUR_CM LIKE ''%METER%''
            THEN SPLIT_PART(pim.HAUTEUR_CM, '' '', 1)::FLOAT
    END AS HAUTEUR_METRE
FROM pim
LEFT JOIN IRRI_DEV.SILVER.ARTICLE_X3_ATTRIBUTES x3 ON pim.SKU = x3.CODE';

    EXECUTE IMMEDIATE :create_sql;

    EXECUTE IMMEDIATE '
CREATE OR REPLACE DYNAMIC TABLE IRRI_DEV.GOLD.ARTICLE_INFO_COMPLET_SEARCH
    TARGET_LAG = ''1 day''
    REFRESH_MODE = INCREMENTAL
    INITIALIZE = ON_CREATE
    WAREHOUSE = COMPUTE_WH
AS
SELECT ci.*, doc.FULL_DOC AS SEARCH_DOCUMENT
FROM IRRI_DEV.SILVER.ARTICLE_COMPLET_INFO ci
LEFT JOIN IRRI_DEV.SILVER.ARTICLE_SEARCH_DOCUMENT doc ON ci.SKU = doc.SKU';

    RETURN 'Dynamic Table ARTICLE_COMPLET_INFO recreated with ' || ARRAY_SIZE(:new_cols) || ' PIM columns (+ GOLD refreshed)';
END;

CALL IRRI_DEV.SILVER.REBUILD_ARTICLE_COMPLET_INFO();

ALTER DYNAMIC TABLE IRRI_DEV.SILVER.ARTICLE_COMPLET_INFO REFRESH;

-- 2. Task planifiée (1x par jour)
CREATE OR REPLACE TASK IRRI_DEV.SILVER.TASK_REBUILD_ARTICLE_COMPLET_INFO
    WAREHOUSE = COMPUTE_WH
    SCHEDULE = 'USING CRON 0 3 * * * Europe/Paris'
AS
    CALL IRRI_DEV.SILVER.REBUILD_ARTICLE_COMPLET_INFO();

-- 3. Activer la task
ALTER TASK IRRI_DEV.SILVER.TASK_REBUILD_ARTICLE_COMPLET_INFO RESUME;

SELECT DATE_FIN_DE_VIE FROM IRRI_DEV.SILVER.ARTICLE_COMPLET_INFO;